name: Deploy to Azure

on:
  push:
    branches:
      - main  # When pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # fix write permission error in GithubActions

    steps:
      - name: Checkout code  # Checkout the code
        uses: actions/checkout@v2

      - name: Azure login  # Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.REDDITBOT_AZURE_CLIENT_ID}}  # Credentials from GitHub secrets
          tenant-id: ${{ secrets.REDDITBOT_AZURE_TENANT_ID}}  # Credentials from GitHub secrets
          subscription-id: ${{ secrets.REDDITBOT_AZURE_SUBSCRIPTION_ID}}  # Credentials from GitHub secrets

      - name: GitHub Container Registry login  # Setup docker and access the registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}  # Credentials from GitHub secrets

      - name: Deploy to Azure container Apps  # Deploy the container into the Azure environment
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: redditbot
          resourceGroup: redditbot-container
          imageToDeploy: ghcr.io/${{ github.repository_owner | lower }}/redditbot:latest  # Image from GitHub registry
          registryUrl: ghcr.io  # GitHub registry URL
          registryUsername: ${{ github.repository_owner }}
          registryPassword: ${{ secrets.GHCR_TOKEN }}  # Token
          containerAppEnvironment: managedEnvironment-redditbotcontai-b92c  # Azure container environment
          targetPort: 8000
          ingress: external  # Ingress turned on for external access
