# On every push to main, a new docker image will be created
# this will be pushed to github registry so that it can be used in other workflows and not only exist locally
#For example it can be deployed to a cloud
name: Docker Build and Push

on:
  push:
    branches: [ "main" ]  # when pushed to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        #Try to convert the repository owner name string to lowercase
      - name: Convert repository owner to lowercase
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU (for cross-platform builds, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # login to GitHub Container Reg
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build and Push Docker Image container reg
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true  # Enable push to registry
          tags: ghcr.io/${{ env.REPO_OWNER }}/reddit-discord-bot:latest
